import { Product } from '../../products'

export const PRODUCTDUMMY: { [key: string]: Product } = {
    MODELDUMMY1: {
        name: 'Solitaire Diamond Ring',
        description: 'A classic and timeless solitaire diamond ring set in 14k white gold',
        type: 'ring',
        material: '14k white gold, diamond',
        price: 1999,
        category: 'diamond',
        stock: 5,
    },
    MODELDUMMY2: {
        name: 'Gold Hoop Earrings',
        description: 'A pair of large gold hoop earrings, perfect for everyday wear',
        type: 'earrings',
        material: '14k yellow gold',
        price: 299,
        category: 'gold',
        stock: 10,
    },
    MODELDUMMY3: {
        name: 'Sterling Silver Necklace',
        description: 'A delicate sterling silver necklace with a small pendant',
        type: 'necklace',
        material: 'sterling silver',
        price: 99,
        category: 'silver',
        stock: 15,
    },
    MODELDUMMY4: {
        name: 'Platinum Wedding Band',
        description: 'A simple and elegant platinum wedding band',
        type: 'ring',
        material: 'platinum',
        price: 599,
        category: 'platinum',
        stock: 8,
    },
    MODELDUMMY5: {
        name: 'Pearl Bracelet',
        description: 'A classic pearl bracelet set in 14k white gold',
        type: 'bracelet',
        material: '14k white gold, pearls',
        price: 399,
        category: 'pearl',
        stock: 12,
    },
    MODELDUMMY6: {
        name: 'Diamond Stud Earrings',
        description: 'A pair of round diamond stud earrings set in 14k white gold',
        type: 'earrings',
        material: '14k white gold, diamonds',
        price: 1499,
        category: 'diamond',
        stock: 6,
    },
}
